### ISSUE TITLE
Make Docker image for CORL software

### ISSUE THREAD

**Issue by peteflorence** [RobotLocomotion/spartan#104]
Everybody want this.  Targeting to do after June 28.

**Comment by EricCousineau-TRI** [comment]
If it's a useful reference, [here is Brandon's PR](https://github.com/RobotLocomotion/drake/pull/6196) for adding Docker to Drake; I believe he is planning to test `nvidia-docker`, to run `drake-visualizer` from within the docker image.

**Comment by peteflorence** [comment]
Thanks Eric!

On Thu, Jun 15, 2017 at 1:36 PM, EricCousineau-TRI <notifications@github.com

**Comment by manuelli** [comment]
Seems like this has happened already with the switch to LabelFusion.

**Comment by patmarion** [comment]
Not exactly, the Docker image for LabelFusion only includes Director and ElasticFusion, not Spartan.  But the scripts for creating the LabelFusion Docker image could be easily ported to Spartan to create a Spartan docker image.

**Comment by peteflorence** [comment]
Closing this issue since we now have:

- a dedicated [LabelFusion docker container](https://hub.docker.com/r/robotlocomotion/labelfusion/) in which LabelFusion works great
- [a full Spartan docker build](https://github.com/RobotLocomotion/spartan/blob/master/setup/docker/README.md).  Even though we haven't tested LabelFusion inside it.
