### ISSUE TITLE
missing drake submodule snopt

### ISSUE THREAD

**Issue by YuehChuan** [RobotLocomotion/spartan#124]
![drake-snort](https://user-images.githubusercontent.com/7314531/30234743-bdf9457a-9532-11e7-9bf4-5f5b1c1fb5a6.png)

**Comment by YuehChuan** [comment]
temperately I remove the submodule seems it optional nonlinear optimization library
https://gist.github.com/kyleturner/1563153 
and turn off CMake configure
It would be good to add that in organization repo, thanks!

**Comment by manuelli** [comment]
`snopt` is a private submodule not accessible to outside users. You can turn off the `WITH_SNOPT` option in the `drake` build to fall back to using `ipopt`. In general `spartan` is meant for internal use and we won't be providing support to external users for the time being.

**Comment by YuehChuan** [comment]
It got compiled! Thanks for making this project available!
