### ISSUE TITLE
Launch drake executables with `bazel run` syntax

### ISSUE THREAD

**Issue by manuelli** [RobotLocomotion/spartan#139]
Currently we have the short term solution of copying the executables from the `drake` `.bazel` folder as in #138

**Comment by rdeits** [comment]
FYI: `bazel run` for one command will block all other `bazel run` and `bazel build` commands on your system, so this might not be a good idea: https://github.com/RobotLocomotion/drake/issues/6855

**Comment by fbudin69500** [comment]
Why not running the executables that are installed? Am I missing a piece of information?

**Comment by manuelli** [comment]
I don't think that all the executables we want are currently installed. For example `kuka_simulation` or `iiwa_wsg_simulation`

**Comment by gizatt** [comment]
That's a thing that we should fix as we figure out what we need!

My sim development branch will have us compiling our own versions of those files, btw, as I'm making some modifications to what they broadcast / how they set up their environment.

**Comment by manuelli** [comment]
As of #310 we will no longer be consuming any `drake` executables.
