### ISSUE TITLE
Faster setup for new Dockerized Spartan

### ISSUE THREAD

**Issue by peteflorence** [RobotLocomotion/spartan#145]
This is not number 1 priority for now (all the base tools are now working in Docker), but if/when we have time later, it would be good to lower the amount of time needed to create a fresh Dockerized installation of Spartan.  

I just timed how long this process currently takes and it roughly broke down to:

- ~1 minute to git clone, submodule init, submodule update all modules
- ~9 minutes to do docker_build (which is just apt-get installing)
- ~6 minutes to build drake
- ~10 minutes to build director and pcl

~26 minutes total

Also noting how long some recent options take:
- 7 minutes for apt-getting everything for ElasticFusion
- 2 minutes to build mini director and elasticfusion after apt-installs
- 3 minutes to apt-get install ros-kinetic-desktop-full

**Comment by manuelli** [comment]
Not a priority for now
