### ISSUE TITLE
no lcm-logplayer-gui executable in spartan

### ISSUE THREAD

**Issue by manuelli** [RobotLocomotion/spartan#149]
This must have gotten lost in the `bazel` transition. @fbudin69500 @jamiesnape

**Comment by sammy-tri** [comment]
I also noticed this recently, would be good to have it back.

**Comment by jamiesnape** [comment]
Which repo is it in? libbot or LCM?

**Comment by manuelli** [comment]
I think it's in `lcm`. A quick google search turned up this https://github.com/lcm-proj/lcm/blob/master/lcm-java/lcm-logplayer-gui.1

**Comment by jamiesnape** [comment]
That would need to be built in Drake, I guess. We are moving the libbot build out of Drake, but LCM would need to stay there.

**Comment by peteflorence** [comment]
+1 for this -- `lcm-logplayer-gui` is a core tool

**Comment by manuelli** [comment]
The executable is now there.
