### ISSUE TITLE
Add sensors to iiwa sim

### ISSUE THREAD

**Issue by manuelli** [RobotLocomotion/spartan#179]
Add the ability to simulate depth/color sensors in the iiwa drake sim. It should publish out messages via ROS, presumably on the PointCloud2 channel.

@stonier is this already supported in drake? If so could you point us to an example. It would be nice to be able to dynamically specify the camera location at runtime since it is usually read from a calibration config file.

**Comment by gizatt** [comment]
I have a half-baked version of this that needs updating on the `iiwa_rlg_simulation` branch

**Comment by manuelli** [comment]
This is now in master using the PyBullet sim
