### ISSUE TITLE
Add ROS driver for schunk gripper

### ISSUE THREAD

**Issue by manuelli** [RobotLocomotion/spartan#189]
@sammy-tri any thoughts?

**Comment by sammy-tri** [comment]
I have no use for such a thing.

**Comment by sammy-tri** [comment]
That may have been unnecessarily harsh...   The LCM based one is working fine for me and I doubt I'll want to control the gripper using ROS any time in the near future.

**Comment by manuelli** [comment]
Ok, we'll take this over. I think our codebases are rapidly diverging so just wanted to give you the heads up.

**Comment by manuelli** [comment]
Looks like a driver already exists here https://github.com/nalt/wsg50-ros-pkg

**Comment by manuelli** [comment]
After talking with a visitor we should use the [nalt](https://github.com/nalt/wsg50-ros-pkg) driver. They have been using it successfully. @gizatt do you want to take the lead on this?

**Comment by manuelli** [comment]
That's fine, I'm in no rush. We have been using it like this so far, but better to eliminate the red error light from our gripper.

**Comment by gizatt** [comment]
I've perused a few of the options with the nalt driver, and I think the Xamla fork is the most modern / usefully-featured. It's a bit of a mess (it exposes two different actionlib servers with different interfaces and has zero documentatino), but it allows functional enough position, speed, and force control with real-time feedback. I'll start switching things over to that driver.

**Comment by manuelli** [comment]
This is in master
