### ISSUE TITLE
SR300 Software side

### ISSUE THREAD

**Issue by gizatt** [RobotLocomotion/spartan#203]
Do something similar to cameraconfig for SR300 to get it up and running easily

**Comment by manuelli** [comment]
I think creating a launch file in the `camera_config` package similar to [this](https://github.com/RobotLocomotion/spartan/blob/master/src/catkin_projects/camera_config/launch/openni2.launch) would work well.

**Comment by manuelli** [comment]
Seems like this is on the back burner for now.
