### ISSUE TITLE
docker_run only compatible with python 2

### ISSUE THREAD

**Issue by gizatt** [RobotLocomotion/spartan#204]
```
  File "./setup/docker/docker_run.py", line 23
    print "running docker container derived from image %s" %args.image
                                                         ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("running docker container derived from image %s" %args.image)?
```

**Comment by gizatt** [comment]
To be clear: not proposing a massive compat overhaul for python 3, just noting one issue that makes invoking `docker_run` a little more annoying :)

**Comment by manuelli** [comment]
AFAIK the `print` statment is the big difference between Python2 and Python3. If there is some sort of print statment that works for both of them I am happy to switch to that. Also wrapping in try/catch is fine.

**Comment by rdeits** [comment]
At the top of the file, add:

```python
from __future__ import print_function
```

then change all `print "foo"` to `print("foo")` (i.e. python3 style) and the code will work in both Python2 and Python3

**Comment by manuelli** [comment]
Thanks for the tip Robin!
