### ISSUE TITLE
Errors finding lcm shared library

### ISSUE THREAD

**Issue by manuelli** [RobotLocomotion/spartan#220]
These errors occur when buidling `ContactParticleFilter` or `spartan_lcmtypes`. The error is

```
/home/manuelli/spartan/build/install/bin/lcm-gen: error while loading shared libraries: liblcm.so: cannot open shared object file: No such file or directory
cpf_lcmtypes/lcmtypes/CMakeFiles/lcmtypes_cpf-lcm.sources.dir/build.make:80: recipe for target 'cpf_lcmtypes/lcmtypes/cpf_lcmtypes_actual_and_estimated_contact_locations_t.h' failed
make[6]: *** [cpf_lcmtypes/lcmtypes/cpf_lcmtypes_actual_and_estimated_contact_locations_t.h] Error 127
CMakeFiles/Makefile2:108: recipe for target 'cpf_lcmtypes/lcmtypes/CMakeFiles/lcmtypes_cpf-lcm.sources.dir/all' failed
make[5]: *** [cpf_lcmtypes/lcmtypes/CMakeFiles/lcmtypes_cpf-lcm.sources.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make[4]: *** [all] Error 2
CMakeFiles/ContactParticleFilter.dir/build.make:112: recipe for target 'src/ContactParticleFilter-stamp/ContactParticleFilter-build' failed

```

somehow we are having problems with finding the lcm provided by `drake`. The other option is to simply system install lcm and use that.

The quick fix for now is to disable `spartan_lcmtypes` and `ContactParticleFilter` in the build as they are not currently being used.

**Comment by peteflorence** [comment]
+1 for running into this issue for a fresh install on my own computer

**Comment by manuelli** [comment]
We should investigate why this isn't being caught by the build machine. That's somehow the more serious issue.

**Comment by gizatt** [comment]
Is this related to the discussion on
https://github.com/RobotLocomotion/spartan/pull/211? CI caught this error
and it was fixed with an additional required step in the build process.

**Comment by peteflorence** [comment]
I'm doing some experimenting, will report back in a second

**Comment by peteflorence** [comment]
Okay I was able to build with `ContactParticleFilter` and `spartan_lcmtypes`

It's possible that previously I didn't follow this order in build process:

```
use_ros && cmake .. && use_spartan && make -j8
```

I can now make everything, if I use that order.

**Comment by gizatt** [comment]
I suspect

```use_ros && use_spartan && cmake .. && make -j8```

ought to work too. But yeah, `use_spartan` must happen after `cmake` (so
that the script it calls is generated) but before `make`, which must be
able to find lcm-gen that is built and installed by previous steps in
`make.`

**Comment by manuelli** [comment]
Ok I may have messed up the `use_spartan` stuff, but I thought I did it correctly. I will investigate as well.

**Comment by manuelli** [comment]
Seems like this was due to incorrect build procedure. Closing
