### ISSUE TITLE
GPU usage at 100% when running pybullet sim

### ISSUE THREAD

**Issue by manuelli** [RobotLocomotion/spartan#244]
This is due to inefficiencies in RemoteTreeViewer. Hacky fix for now is to set a speed limit on the remote tree viewer subscriber. In the `director` python terminal run

```
hz = 2
treeViewer.subscriber.setSpeedLimit(hz)
```

You can also do this programmatically in the launch script.

**Comment by rdeits** [comment]
What does pybullet sim do? Is it publishing `setgeometry` every tick?

**Comment by gizatt** [comment]
Yuuuup

**Comment by rdeits** [comment]
Judging from the Python bindings, it looks like the geometry is probably getting loaded at every tick, which is definitely going to use up your GPU. The right thing to do would be to only do setgeometry once and the use settransform to move the mesh around. That should drastically reduce the GPU load even at high framerates.

**Comment by rdeits** [comment]
Ah, ok, yeah. Don't do that :-p

**Comment by manuelli** [comment]
@gizatt any progress on this?

**Comment by gizatt** [comment]
I know the cause and solution -- would be a few hours to get it done,
though. How high priority is it for you? If its causing trouble I'm happy
to fix it

**Comment by manuelli** [comment]
Not high priority at all. Just want to make sure it doesn't fall through the cracks.

**Comment by manuelli** [comment]
Have switched to drake sim so this is no longer relevant
