### ISSUE TITLE
Integrate Kuka stopping code with spartan master

### ISSUE THREAD

**Issue by kmuhlrad** [RobotLocomotion/spartan#253]
As of commit [9167796](https://github.com/RobotLocomotion/drake/commit/91677965fa4e11e77c4f69afc14210a1fe68e70b) in drake master, code that allows the Kukas to stop upon an LCM request has been integrated. It would be helpful to build spartan off of that commit or a later one to pull these changes into spartan so we can use them for more GelSight testing.

**Comment by manuelli** [comment]
Addressed by #254
