### ISSUE TITLE
Xtion sensor: Failed to open the USB device!

### ISSUE THREAD

**Issue by MannyKayy** [RobotLocomotion/spartan#263]
Attempting to use an Xtion Live Pro with the provided docker environment and get the following error when executing `roslaunch camera_config openni2.launch`:

![image](https://user-images.githubusercontent.com/7952854/37246365-f379f49a-249f-11e8-9fdb-c986b0fd6925.png)

There was a [similar error](https://github.com/RobotLocomotion/LabelFusion/issues/18) in the LabelFusion repository. And the fix suggested in the mentioned branch worked for the LabelFusion docker environment.

System:
- Ubuntu 16.04
- Xtion Pro Live.
- [Lenovo Thinkpad P50](http://static.lenovo.com/shop/emea/content/pdf/ThinkPad/P%20Series/P50DSEN.pdf)

**Comment by manuelli** [comment]
We already pass the `--priveleged` flag to the docker environment. On our computers the xtion's have always had problems with the openni driver so I don't think this is a new issue.
