### ISSUE TITLE
Mount data folder on host machine into the docker as sandbox workspace

### ISSUE THREAD

**Issue by manuelli** [RobotLocomotion/spartan#271]
Currently we are putting large files into `sandbox` and `calibration/data` folders. It would be better to mount a folder into the docker image so we don't increase the size of files under `spartan`. Otherwise the docker build command is very slow because it has to copy all that over.

**Comment by peteflorence** [comment]
Seems like this will be addressed by https://github.com/RobotLocomotion/spartan/pull/280
