### ISSUE TITLE
apriltags_driver build fails looking for eigen3

### ISSUE THREAD

**Issue by sammy-tri** [RobotLocomotion/spartan#28]
During the director build, while running cmake for apriltags_driver, it fails to find eigen3 (specifically `eigen3.pc` since it's using pods afaict).  This seems to be because `eigen3.pc` is in `build/install/share/pkgconfig` instead of `build/install/lib/pkgconfig` (where all of the other `.pc` files are).  Copying eigen3.pc into `build/install/lib/pkgconfig` seems to fix matters for that build, but I'm not sure how it's landing out of place to begin with.

**Comment by manuelli** [comment]
Just did a clean build and didn't have this issue. `libeigen3-dev` is now in `install_prereqs.sh` as well.
