### ISSUE TITLE
Jenkins build machine out of HD space

### ISSUE THREAD

**Issue by manuelli** [RobotLocomotion/spartan#288]
@gizatt I just checked the `spartan` build machine and noticed that it was out of hard disk space. This was because `/var/logs/jenkins` was 350GB. Is there a way to avoid keeping these old build logs around so this doesn't happen again?

**Comment by gizatt** [comment]
Ah, makes sense. I just tweaked the build configs to delete logs from more than 30 builds ago (for PR testing) and 10 builds ago (for nightly). Hopefully that helps?

(Given that Jenkins is working again, did you delete those old logs already?)

**Comment by manuelli** [comment]
Yes I deleted them manually and it's working again. Those tweaks seem like they should do the trick! Thanks @gizatt
