### ISSUE TITLE
unittests not reliable

### ISSUE THREAD

**Issue by manuelli** [RobotLocomotion/spartan#315]
We need a way of efficiently starting/stopping the procman sheriff and deputy reliably. It's not working well in the python unittest framework right now and tests are failing spuriously.

@gizatt could you take a look if you have time?

**Comment by gizatt** [comment]
Happy to look at, though I'm gonna put this relatively low on my stack for the next few days

**Comment by gizatt** [comment]
I think #320 fixed this, judging by the relative stability of the non-drake-master branches. (I see the issue on the Drake master branch, it's a build issue.)

**Comment by manuelli** [comment]
Yup agreed it's fixed, thanks!
