### ISSUE TITLE
Submodule issue with razer hydra

### ISSUE THREAD

**Issue by manuelli** [RobotLocomotion/spartan#329]
During `git submodule update --init --remote` I get the error

```
Cloning into 'src/catkin_projects/razer_hydra_ros'...
remote: Counting objects: 274, done.
remote: Total 274 (delta 0), reused 0 (delta 0), pack-reused 274
Receiving objects: 100% (274/274), 49.09 KiB | 0 bytes/s, done.
Resolving deltas: 100% (104/104), done.
Checking connectivity... done.
fatal: Needed a single revision
Unable to find current origin/master revision in submodule path 'src/catkin_projects/razer_hydra_ros'
```

**Comment by gizatt** [comment]
What's --remote? I probably didnt configure it correctly to work with that?

**Comment by manuelli** [comment]
I'm investigating now. I am switching it to ssh instead of https, seeing if that works.

**Comment by manuelli** [comment]
Yeah I think we just want `git submodule update --init`, not `git submodule update --init --remote`.

**Comment by gizatt** [comment]
Thought so, thats what I use on CI and personally

**Comment by manuelli** [comment]
Cool, I'll just update the README then.
