### ISSUE TITLE
build error looking for wsg 50 msgs

### ISSUE THREAD

**Issue by peteflorence** [RobotLocomotion/spartan#339]
@gizatt @manuelli 

Hey guys, I believe temporarily fixed this by nuking `drake-schunk-driver`, which seems to be vestigial?  Potentially may be worth fully removing from git?  There are a handful of tricky steps including removing from .gitmodules, see below.  I imagine this doesn't happen on new builds, since Jenkins passes

https://github.com/RobotLocomotion/spartan/blob/d868924c6b348566c1fc130d5d84a519fc137b57/.gitmodules#L19

**Comment by gizatt** [comment]
Thought I had fixed this, but yeah, looks like it but needs to be cleaned from `.gitmodules`. In the mean time, manually removing the `drake-schunk-driver` folder fixes this... and it shouldn't occur on new, clean clones of the repo, agreed.

**Comment by gizatt** [comment]
Resolved, I think, by PR#340. LMK if not?
