### ISSUE TITLE
Cleanup project-specific/unused code

### ISSUE THREAD

**Issue by weigao95** [RobotLocomotion/spartan#378]
As we discussed, spartan becomes messy as we have merged lots of project-specific code into the master. We should clean them up and keep only the core modules at master. In the future, each project should maintain its own fork/branch. Only code that everyone would (potentially) use can be merged into master.

After finalizing what to keep/remove, we should make PRs for the cleanup. Here is a tentative proposal.

### What to keep
Robot driver and plan runner:
- catkin_projects/iiwa_driver
- catkin_projects/station_config
- catkin_projects/robot_msgs
- catkin_projects/robot_server
- catkin_projects/robot_control
- catkin_projects/drake_robot_control
- catkin_projects/wsg50-ros-pkg
- modules/spartan/utils
- modules/spartan/manipulation/schunk_driver.py

Camera driver and calibration:
- catkin_projects/camera_config
- handical
- modules/spartan/calibration

Simulation and teleop tools:
- catkin_projects/drake_iiwa_sim
- catkin_projects/simple_teleop

Visualization:
- director
- signal-scope

### What to remove
Everything except above (and the dependency of above)

**Comment by peteflorence** [comment]
Thanks Wei for putting this together! Looking forward to discussing and
figuring out.
