### ISSUE TITLE
no such package '@snopt//'

### ISSUE THREAD

**Issue by Amulya21** [RobotLocomotion/spartan#382]
Repository rule snopt error 128 during git operation: "Cloning into '.'...\nERROR: Repository not found.\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"

what to do?

**Comment by manuelli** [comment]
Hi,

As stated on the main README `spartan` not supported for public use. The error you are getting is due to a private submodule.
