### ISSUE TITLE
Dev Workflow Plan  (w/ Drake)

### ISSUE THREAD

**Issue by stonier** [RobotLocomotion/spartan#68]
**Goals**

1. a working sample of how to work with drake from a cmake project
2. allow users to work with binaries of drake
3. allow power users to work with a source built version of drake

**Short Term**

* [ ] Replace the `ExternalProject_Add` for the bazel built version of drake. This enables us to test the bazel installed implementation without having to additionally deal with changing people's workflows (PR #116) 

**Mid Term**

Adjust the humans' workflow:

* [ ] *users*: `find_package` with versioned, bundled drake binaries (debs) (i.e. incl eigen and the rest) on xenial
* [ ]  *power users*: `find_package` with parallel drake source workspace and `drake_DIR` or `CMAKE_PREFIX_PATH` mechanisms

**Long Term**

* *users*: `find_package` with versioned, system compatible drake binaries (debs) on xenial

**Comment by peteflorence** [comment]
Hi @stonier @mwoehlke-kitware is there anything else you want to do before closing this issue?

Spartan is building against bazel-built Drake just fine now.  I'm not sure all your stated objectives have been met but wanted to check in.

**Comment by peteflorence** [comment]
I think the goals laid out in this issue have been achieved, so closing.  Somebody feel free to reopen if you feel differently.
